# Extra Questions extracted directly from Teacher's Sample Papers (samples/Maths/1.jpg, 2.jpg, 3.jpg)
# and additional textbook questions for Class 5, 6, and 7 Maths.

SAMPLE_QUESTIONS_7_MATHS = [
  # --- Section A: Formulas & Definitions ---
  {
    "id": "7m_sample_f1",
    "subjectId": "7_maths",
    "sectionKey": "sec_a",
    "set": "Sample Paper",
    "orderInSet": 1,
    "originalNum": "Q1(i)",
    "marks": 1,
    "chapter": "Ch 11: Perimeter, Area & Speed (परिमाप, क्षेत्रफल एवं चाल)",
    "hasOrChoice": False,
    "preview": "Formula for Area of Parallelogram / समान्तर चतुर्भुज का क्षेत्रफल",
    "content": "**State the formula for Area of a Parallelogram.**  \n**समान्तर चतुर्भुज का क्षेत्रफल ज्ञात करने का सूत्र बताइए:**  \n$$\\text{Area of Parallelogram} = \\text{Base} \\times \\text{Height} / \\text{आधार} \\times \\text{ऊँचाई}$$"
  },
  {
    "id": "7m_sample_f2",
    "subjectId": "7_maths",
    "sectionKey": "sec_a",
    "set": "Sample Paper",
    "orderInSet": 2,
    "originalNum": "Q1(ii)",
    "marks": 1,
    "chapter": "Ch 11: Perimeter, Area & Speed (परिमाप, क्षेत्रफल एवं चाल)",
    "hasOrChoice": False,
    "preview": "Formula for Area of Triangle / त्रिभुज का क्षेत्रफल",
    "content": "**State the formula for Area of a Triangle.**  \n**त्रिभुज का क्षेत्रफल ज्ञात करने का सूत्र बताइए:**  \n$$\\text{Area of Triangle} = \\frac{1}{2} \\times \\text{Base} \\times \\text{Height} / \\frac{1}{2} \\times \\text{आधार} \\times \\text{ऊँचाई}$$"
  },
  {
    "id": "7m_sample_f3",
    "subjectId": "7_maths",
    "sectionKey": "sec_a",
    "set": "Sample Paper",
    "orderInSet": 3,
    "originalNum": "Q1(iii)",
    "marks": 1,
    "chapter": "Ch 5: Exponents and Powers (घातांक और घात)",
    "hasOrChoice": False,
    "preview": "Law of exponents: a^m × a^n",
    "content": "**Complete the law of exponents:**  \n**घातांक के नियम को पूरा कीजिए:**  \n$$a^m \\times a^n = \\underline{\\hspace{1.5cm}}$$"
  },
  {
    "id": "7m_sample_f4",
    "subjectId": "7_maths",
    "sectionKey": "sec_a",
    "set": "Sample Paper",
    "orderInSet": 4,
    "originalNum": "Q1(iv)",
    "marks": 1,
    "chapter": "Ch 5: Exponents and Powers (घातांक और घात)",
    "hasOrChoice": False,
    "preview": "Law of exponents: (a^m)^n",
    "content": "**Complete the law of exponents:**  \n**घातांक के नियम को पूरा कीजिए:**  \n$$(a^m)^n = \\underline{\\hspace{1.5cm}}$$"
  },
  {
    "id": "7m_sample_f5",
    "subjectId": "7_maths",
    "sectionKey": "sec_a",
    "set": "Sample Paper",
    "orderInSet": 5,
    "originalNum": "Q1(v)",
    "marks": 1,
    "chapter": "Ch 11: Perimeter, Area & Speed (परिमाप, क्षेत्रफल एवं चाल)",
    "hasOrChoice": False,
    "preview": "Formula for Circumference of Circle / वृत्त की परिधि",
    "content": "**State the formula for the Circumference of a Circle with radius $r$.**  \n**त्रिज्या $r$ वाले वृत्त की परिधि का सूत्र लिखिए:**  \n$$\\text{Circumference (परिधि)} = 2\\pi r$$"
  },
  {
    "id": "7m_sample_d1",
    "subjectId": "7_maths",
    "sectionKey": "sec_a",
    "set": "Sample Paper",
    "orderInSet": 6,
    "originalNum": "Q2(i)",
    "marks": 1,
    "chapter": "Ch 14: Symmetry (सममिति)",
    "hasOrChoice": False,
    "preview": "Definition: Angle of Rotation / घूर्णन का कोण",
    "content": "**Define Angle of Rotation with an example.**  \n**घूर्णन का कोण (Angle of rotation) की परिभाषा लिखिए।**"
  },
  {
    "id": "7m_sample_d2",
    "subjectId": "7_maths",
    "sectionKey": "sec_a",
    "set": "Sample Paper",
    "orderInSet": 7,
    "originalNum": "Q2(ii)",
    "marks": 1,
    "chapter": "Ch 12: Algebraic Expressions (बीजीय व्यंजक)",
    "hasOrChoice": False,
    "preview": "Definition: Polynomial / बहुपद",
    "content": "**Define a Polynomial in algebra.**  \n**बीजगणित में बहुपद (Polynomial) की परिभाषा लिखिए।**"
  },
  {
    "id": "7m_sample_d3",
    "subjectId": "7_maths",
    "sectionKey": "sec_a",
    "set": "Sample Paper",
    "orderInSet": 8,
    "originalNum": "Q2(iii)",
    "marks": 1,
    "chapter": "Ch 11: Perimeter, Area & Speed (परिमाप, क्षेत्रफल एवं चाल)",
    "hasOrChoice": False,
    "preview": "Definition: Circumference of Circle / परिधि",
    "content": "**Define the Circumference of a circle.**  \n**वृत्त की परिधि (Circumference) की परिभाषा लिखिए।**"
  },
  {
    "id": "7m_sample_d4",
    "subjectId": "7_maths",
    "sectionKey": "sec_a",
    "set": "Sample Paper",
    "orderInSet": 9,
    "originalNum": "Q2(iv)",
    "marks": 1,
    "chapter": "Ch 9: Rational Numbers (परिमेय संख्याएँ)",
    "hasOrChoice": False,
    "preview": "Definition: Rational Numbers / परिमेय संख्याएँ",
    "content": "**Define a Rational Number. Give two examples.**  \n**परिमेय संख्या (Rational number) की परिभाषा लिखिए तथा दो उदाहरण दीजिए।**"
  },

  # --- Section B: MCQs & True/False with Justification ---
  {
    "id": "7m_sample_tf1",
    "subjectId": "7_maths",
    "sectionKey": "sec_b",
    "set": "Sample Paper",
    "orderInSet": 10,
    "originalNum": "Q9(i)",
    "marks": 1,
    "chapter": "Ch 5: Exponents and Powers (घातांक और घात)",
    "hasOrChoice": False,
    "preview": "True or False: 2^3 > 5^2",
    "content": "**State True (T) or False (F) and justify: $2^3 > 5^2$.**  \n**सत्य अथवा असत्य बताइए और कारण स्पष्ट कीजिए: $2^3 > 5^2$।**"
  },
  {
    "id": "7m_sample_tf2",
    "subjectId": "7_maths",
    "sectionKey": "sec_b",
    "set": "Sample Paper",
    "orderInSet": 11,
    "originalNum": "Q9(ii)",
    "marks": 1,
    "chapter": "Ch 5: Exponents and Powers (घातांक और घात)",
    "hasOrChoice": False,
    "preview": "True or False: 3^0 = (1000)^0",
    "content": "**State True (T) or False (F) and justify: $3^0 = (1000)^0$.**  \n**सत्य अथवा असत्य बताइए और कारण स्पष्ट कीजिए: $3^0 = (1000)^0$।**"
  },
  {
    "id": "7m_sample_tf3",
    "subjectId": "7_maths",
    "sectionKey": "sec_b",
    "set": "Sample Paper",
    "orderInSet": 12,
    "originalNum": "Q9(iii)",
    "marks": 1,
    "chapter": "Ch 9: Rational Numbers (परिमेय संख्याएँ)",
    "hasOrChoice": False,
    "preview": "True or False: 3/4 = 9/12",
    "content": "**State True (T) or False (F): The fractions $\\frac{3}{4}$ and $\\frac{9}{12}$ are equivalent.**  \n**सत्य अथवा असत्य बताइए: भिन्न $\\frac{3}{4}$ तथा $\\frac{9}{12}$ तुल्य हैं।**"
  },
  {
    "id": "7m_sample_tf4",
    "subjectId": "7_maths",
    "sectionKey": "sec_b",
    "set": "Sample Paper",
    "orderInSet": 13,
    "originalNum": "Q9(iv)",
    "marks": 1,
    "chapter": "Ch 9: Rational Numbers (परिमेय संख्याएँ)",
    "hasOrChoice": False,
    "preview": "True or False: -5 < 0",
    "content": "**State True (T) or False (F): $-5 < 0$.**  \n**सत्य अथवा असत्य बताइए: $-5 < 0$।**"
  },

  # --- Section C: Patterns, Symmetry & Evaluations (2 Marks) ---
  {
    "id": "7m_sample_c1",
    "subjectId": "7_maths",
    "sectionKey": "sec_c",
    "set": "Sample Paper",
    "orderInSet": 14,
    "originalNum": "Q3(i)",
    "marks": 2,
    "chapter": "Ch 9: Rational Numbers (परिमेय संख्याएँ)",
    "hasOrChoice": False,
    "preview": "Pattern: Write four more rational numbers: -3/5, -6/10, -9/15, -12/20",
    "content": "**Write four more rational numbers in the following pattern:**  \n**निम्नलिखित पैटर्न में चार और परिमेय संख्याएँ लिखिए:**  \n$$\\frac{-3}{5}, \\quad \\frac{-6}{10}, \\quad \\frac{-9}{15}, \\quad \\frac{-12}{20}, \\quad \\underline{\\hspace{1cm}}, \\quad \\underline{\\hspace{1cm}}, \\quad \\underline{\\hspace{1cm}}, \\quad \\underline{\\hspace{1cm}}$$"
  },
  {
    "id": "7m_sample_c2",
    "subjectId": "7_maths",
    "sectionKey": "sec_c",
    "set": "Sample Paper",
    "orderInSet": 15,
    "originalNum": "Q3(ii)",
    "marks": 2,
    "chapter": "Ch 9: Rational Numbers (परिमेय संख्याएँ)",
    "hasOrChoice": False,
    "preview": "Pattern: Write four more rational numbers: 2/-3, 4/-6, 6/-9",
    "content": "**Write four more rational numbers in the following pattern:**  \n**निम्नलिखित पैटर्न में चार और परिमेय संख्याएँ लिखिए:**  \n$$\\frac{2}{-3}, \\quad \\frac{4}{-6}, \\quad \\frac{6}{-9}, \\quad \\underline{\\hspace{1cm}}, \\quad \\underline{\\hspace{1cm}}, \\quad \\underline{\\hspace{1cm}}, \\quad \\underline{\\hspace{1cm}}$$"
  },
  {
    "id": "7m_sample_c3",
    "subjectId": "7_maths",
    "sectionKey": "sec_c",
    "set": "Sample Paper",
    "orderInSet": 16,
    "originalNum": "Q5",
    "marks": 2,
    "chapter": "Ch 12: Algebraic Expressions (बीजीय व्यंजक)",
    "hasOrChoice": False,
    "preview": "Evaluate: If m = 2, find value of (i) m - 2, (ii) (5m/2) - 4",
    "content": "**If $m = 2$, find the numerical value of:**  \n**यदि $m = 2$ हो, तो निम्नलिखित के मान ज्ञात कीजिए:**  \n(a) $m - 2$  \n(b) $\\frac{5m}{2} - 4$"
  },
  {
    "id": "7m_sample_c4",
    "subjectId": "7_maths",
    "sectionKey": "sec_c",
    "set": "Sample Paper",
    "orderInSet": 17,
    "originalNum": "Q6",
    "marks": 2,
    "chapter": "Ch 5: Exponents and Powers (घातांक और घात)",
    "hasOrChoice": False,
    "preview": "Find value of: (i) 2^6, (ii) 5^4",
    "content": "**Find the numerical value of:**  \n**मान ज्ञात कीजिए:**  \n(a) $2^6$  \n(b) $5^4$"
  },
  {
    "id": "7m_sample_c5",
    "subjectId": "7_maths",
    "sectionKey": "sec_c",
    "set": "Sample Paper",
    "orderInSet": 18,
    "originalNum": "Q7",
    "marks": 2,
    "chapter": "Ch 14: Symmetry (सममिति)",
    "hasOrChoice": False,
    "preview": "Lines of symmetry for a circle and a square",
    "content": "**State the number of lines of symmetry for each of the following figures:**  \n**निम्नलिखित आकृतियों के लिए सममिति रेखाओं की संख्या बताइए:**  \n(a) A circle / एक वृत्त  \n(b) A square / एक वर्ग"
  },
  {
    "id": "7m_sample_c6",
    "subjectId": "7_maths",
    "sectionKey": "sec_c",
    "set": "Sample Paper",
    "orderInSet": 19,
    "originalNum": "Q8",
    "marks": 2,
    "chapter": "Ch 15: Visualising Solid Shapes (ठोस आकारों का चित्रण)",
    "hasOrChoice": False,
    "preview": "Net of a die (cube) - fill the missing numbers",
    "content": "**On a standard die (cube), the sum of numbers on opposite faces is always $7$. If one face has $4$, what number is on its opposite face? Name two nets that can fold into a cube.**  \n**एक मानक पासे (घन) पर विपरीत फलकों की संख्याओं का योग सदैव $7$ होता है। यदि एक फलक पर $4$ है, तो इसके विपरीत फलक पर कौन-सी संख्या होगी?**"
  },

  # --- Section D: Short Answer & Simplifications (3 Marks) ---
  {
    "id": "7m_sample_d_tab",
    "subjectId": "7_maths",
    "sectionKey": "sec_d",
    "set": "Sample Paper",
    "orderInSet": 20,
    "originalNum": "Q4",
    "marks": 3,
    "chapter": "Ch 11: Perimeter, Area & Speed (परिमाप, क्षेत्रफल एवं चाल)",
    "hasOrChoice": False,
    "preview": "Find missing values table: Parallelogram Base, Height and Area",
    "content": "**Find the missing values in the table for a parallelogram:**  \n**समान्तर चतुर्भुज के लिए सारणी में अज्ञात मान ज्ञात कीजिए:**\n\n| S.No | Base (आधार) | Height (ऊँचाई) | Area of Parallelogram (क्षेत्रफल) |\n| :---: | :---: | :---: | :---: |\n| (a) | $20\\text{ cm}$ | $\\underline{\\hspace{1.5cm}}$ | $246\\text{ cm}^2$ |\n| (b) | $\\underline{\\hspace{1.5cm}}$ | $8.4\\text{ cm}$ | $48.72\\text{ cm}^2$ |"
  },
  {
    "id": "7m_sample_d_alg",
    "subjectId": "7_maths",
    "sectionKey": "sec_d",
    "set": "Sample Paper",
    "orderInSet": 21,
    "originalNum": "Q11",
    "marks": 3,
    "chapter": "Ch 12: Algebraic Expressions (बीजीय व्यंजक)",
    "hasOrChoice": False,
    "preview": "Simplify the expression and find value if x = 2",
    "content": "**Simplify the algebraic expression and find its value when $x = 2$:**  \n**व्यंजक को सरल कीजिए तथा $x = 2$ होने पर इसका मान ज्ञात कीजिए:**  \n(a) $x + 7 + 4(x - 5)$  \n(b) $4(2x - 1) + 3x + 11$"
  },
  {
    "id": "7m_sample_d_rat",
    "subjectId": "7_maths",
    "sectionKey": "sec_d",
    "set": "Sample Paper",
    "orderInSet": 22,
    "originalNum": "Q12",
    "marks": 3,
    "chapter": "Ch 9: Rational Numbers (परिमेय संख्याएँ)",
    "hasOrChoice": False,
    "preview": "Find the value of rational operations: subtract and multiply",
    "content": "**Find the value of the following rational expressions:**  \n**निम्नलिखित परिमेय व्यंजकों का मान ज्ञात कीजिए:**  \n(a) $\\frac{7}{24} - \\frac{17}{36}$  \n(b) $\\left(-\\frac{3}{7}\\right) \\times \\left(-\\frac{2}{5}\\right)$"
  },
  {
    "id": "7m_sample_d_exp",
    "subjectId": "7_maths",
    "sectionKey": "sec_d",
    "set": "Sample Paper",
    "orderInSet": 23,
    "originalNum": "Q13(i)",
    "marks": 3,
    "chapter": "Ch 5: Exponents and Powers (घातांक और घात)",
    "hasOrChoice": False,
    "preview": "Simplify in exponential form: (3 × 7^2 × 11^8) / (21 × 11^3)",
    "content": "**Simplify and express the result in exponential form:**  \n**सरल कीजिए तथा परिणाम को घातांकीय रूप में व्यक्त कीजिए:**  \n$$\\frac{3 \\times 7^2 \\times 11^8}{21 \\times 11^3}$$"
  },

  # --- Section E: Long Answer, Word Problems & Geometry (4 Marks) ---
  {
    "id": "7m_sample_e_circle",
    "subjectId": "7_maths",
    "sectionKey": "sec_e",
    "set": "Sample Paper",
    "orderInSet": 24,
    "originalNum": "Q10",
    "marks": 4,
    "chapter": "Ch 11: Perimeter, Area & Speed (परिमाप, क्षेत्रफल एवं चाल)",
    "hasOrChoice": True,
    "preview": "Find the area of circles (radius = 14 mm, diameter = 49 m)",
    "content": "**Find the area of the following circles (Take $\\pi = \\frac{22}{7}$):**  \n**निम्नलिखित वृत्तों का क्षेत्रफल ज्ञात कीजिए ($\\pi = \\frac{22}{7}$ लीजिए):**  \n(a) $\\text{Radius} = 14\\text{ mm}$ (2 Marks)  \n(b) $\\text{Diameter} = 49\\text{ m}$ (2 Marks)  \n\n**OR / अथवा**  \n\n**A circular flower bed is surrounded by a path $4\\text{ m}$ wide. The diameter of the flower bed is $66\\text{ m}$. What is the area of this path? (Take $\\pi = 3.14$)**  \n**एक वृत्ताकार फूलों की क्यारी के चारों ओर $4$ मीटर चौड़ा मार्ग है। फूलों की क्यारी का व्यास $66$ मीटर है। इस मार्ग का क्षेत्रफल क्या होगा?**"
  },
  {
    "id": "7m_sample_e_iso",
    "subjectId": "7_maths",
    "sectionKey": "sec_e",
    "set": "Sample Paper",
    "orderInSet": 25,
    "originalNum": "Q14",
    "marks": 4,
    "chapter": "Ch 15: Visualising Solid Shapes (ठोस आकारों का चित्रण)",
    "hasOrChoice": True,
    "preview": "Dimensions of cuboid are 5 cm, 3 cm, 2 cm. Draw isometric sketch",
    "content": "**The dimensions of a cuboid are $5\\text{ cm}, 3\\text{ cm},$ and $2\\text{ cm}$. Draw an isometric sketch and an oblique sketch of this cuboid.**  \n**एक घनाभ की विमाएँ $5$ सेमी, $3$ सेमी और $2$ सेमी हैं। इस घनाभ का एक आइसोमेट्रिक (समदूरिक) रेखाचित्र बनाइए।**  \n\n**OR / अथवा**  \n\n**Draw the net of: (a) A cylinder, (b) A cone, and state the number of faces and vertices for each.**  \n**(a) एक बेलन तथा (b) एक शंकु का जाल (net) बनाइए तथा प्रत्येक के फलकों एवं शीर्षों की संख्या लिखिए।**"
  },
  {
    "id": "7m_sample_e_symm",
    "subjectId": "7_maths",
    "sectionKey": "sec_e",
    "set": "Sample Paper",
    "orderInSet": 26,
    "originalNum": "Q15",
    "marks": 4,
    "chapter": "Ch 14: Symmetry (सममिति)",
    "hasOrChoice": True,
    "preview": "Draw any two figures that have both line symmetry and rotational symmetry",
    "content": "**(a) Draw any two geometric figures that have both line symmetry and rotational symmetry. (2 Marks)**  \n**किन्हीं दो ज्यामितीय आकृतियों के चित्र बनाइए जिनमें रेखा सममिति और घूर्णन सममिति दोनों हों।**  \n**(b) For an equilateral triangle, find: (1) Number of lines of symmetry, (2) Order of rotational symmetry. (2 Marks)**  \n**एक समबाहु त्रिभुज के लिए ज्ञात कीजिए: (1) सममिति रेखाओं की संख्या, (2) घूर्णन सममिति का क्रम।**  \n\n**OR / अथवा**  \n\n**Give an example of a geometrical shape which has: (a) Line symmetry but no rotational symmetry, (b) Rotational symmetry of order more than 1 but no line symmetry.**  \n**ऐसी ज्यामितीय आकृति का उदाहरण दीजिए जिसमें: (a) केवल रेखा सममिति हो किंतु घूर्णन सममिति न हो, (b) 1 से अधिक क्रम की घूर्णन सममिति हो किंतु कोई रेखा सममिति न हो।**"
  },
  {
    "id": "7m_sample_e_calc",
    "subjectId": "7_maths",
    "sectionKey": "sec_e",
    "set": "Sample Paper",
    "orderInSet": 27,
    "originalNum": "Q13(iii)",
    "marks": 4,
    "chapter": "Ch 5: Exponents and Powers (घातांक और घात)",
    "hasOrChoice": True,
    "preview": "Simplify: (25 × 5^2 × t^8) / (10^3 × t^4) and (3^5 × 10^5 × 25) / (5^7 × 6^5)",
    "content": "**Simplify using exponential laws:**  \n**घातांक के नियमों का प्रयोग करते हुए सरल कीजिए:**  \n$$\\frac{25 \\times 5^2 \\times t^8}{10^3 \\times t^4} \\quad (t \\neq 0)$$  \n\n**OR / अथवा**  \n\n**Evaluate:**  \n**मान ज्ञात कीजिए:**  \n$$\\frac{3^5 \\times 10^5 \\times 25}{5^7 \\times 6^5}$$"
  }
]

print(f"Sample questions count: {len(SAMPLE_QUESTIONS_7_MATHS)}")
